---
name: Automatically create and deploy to gh-pages branch on same repo
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  clone-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install the dependencies and fix possible security issues
        run: |
          echo "Node version - $(node --version) . NPM version - $(npm --version)"
          npm install
      - name: Deploy to the gh-pages branch
        run: |
          npm run deploy
